services:
  web:
    build: .
    volumes:
      - ./data:/app/data
      - ./appsettings.json:/app/appsettings.json
    networks:
      1panel-network:
        aliases:
          - hyplayerweb

networks:
  1panel-network:
    external: true